version: "3.9"

services:
  be:
    image: captrivia-be
    ports:
      - "8080:8080"
  fe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - be
